workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - flutter clean
      - flutter pub get
      - cd ios && pod install
      - flutter build ios --release --no-codesign  # Construit l’application sans signature
      - xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -archivePath build/ios/archive/Runner.xcarchive archive  # Crée l’archive
      - xcodebuild -exportArchive -archivePath build/ios/archive/Runner.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath build/ios/ipa  # Exporte en IPA
    artifacts:
      - build/ios/ipa/*.ipa  # Récupère l’IPA
    publishing:
      email:
        recipients:
          - evenvo.code@gmail.com  # Remplacez par votre email pour recevoir l'IPA
