workflows:
  ios-workflow:
    name: Workflow iOS
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Installer les dépendances Flutter
        script: |
          flutter pub get
      - name: Installer les pods iOS
        script: |
          cd ios
          pod install --repo-update
      - name: Construire l'application iOS
        script: |
          flutter build ios --release --no-codesign
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release archive -archivePath build/Runner.xcarchive
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/output
    artifacts:
      - build/output/*.ipa