workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - flutter clean
      - flutter pub get
      - cd ios && pod install
      - echo "Starting IPA build"
      - flutter build ios --no-codesign --release
      - echo "IPA build completed"
    artifacts:
      - build/ios/iphoneos/*.ipa