workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - flutter clean
      - flutter pub get
      - cd ios && pod install
      - flutter build ipa --release --no-codesign --export-method development
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive  # Inclut l’archive si besoin
    publishing:
      email:
        recipients:
          - evenvo.code@gmail.com  # Remplacez par votre email pour recevoir l'IPA
