workflows:
  android-workflow:
    name: Android Build
    environment:
      flutter: stable
      android_sdk: latest
    scripts:
      - flutter clean
      - flutter pub get
      - cd android && ./gradlew clean  # Nettoie le projet Android
      - flutter build apk --release --no-codesign  # Génère un APK non signé
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk  # Chemin de l'APK