workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Install CocoaPods
        script: cd ios && pod install
      - name: Build IPA without signing
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - evenvo.code@gmail.com  # Remplacez par votre email pour recevoir l'IPA