workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - flutter clean
      - flutter pub get
      - cd ios && pod install
      - flutter build ipa --release --no-codesign --export-method ad-hoc  # Construit et exporte un IPA non signé
    artifacts:
      - build/ios/ipa/*.ipa  # Récupère l’IPA dans les Artifacts