workflows:
  android-workflow:
    name: Android Build
    environment:
      flutter: stable
    scripts:
      - flutter clean
      - flutter pub get
      - |
        if [ -f android/gradlew ]; then
          cd android && chmod +x gradlew && ./gradlew clean
          echo "Gradle clean executed successfully"
        else
          echo "gradlew not found, skipping Gradle clean"
        fi
      - flutter build apk --release --no-codesign  # Génère un APK non signé
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk  # Chemin de l'APK