workflows:
  ios-workflow:
    name: WORKFLOW_IOS
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Installer les dépendances Flutter
        script: |
          flutter pub get
      - name: Installer les pods iOS
        script: |
          cd ios
          pod install
      - name: Construire l’application iOS (non signé)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
