workflows:
  android-workflow:
    name: Android Build
    environment:
      flutter: stable
    scripts:
      - name: "Get dependencies"
        script: flutter pub get
      - name: "Clean project"
        script: flutter clean
      - name: "Build APK"
        script: flutter build apk --release
      - name: "Echo success"
        script: echo "APK created successfully"
    artifacts:
      - build/app/outputs/flutter-apk/*.apk