// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPeamAYQmWeeOf8AX_J2rcQRRyKS22gr8',
    appId: '1:669049175529:web:2ee6dbd0510a03bd98df78',
    messagingSenderId: '669049175529',
    projectId: 'nocevent-20791',
    authDomain: 'nocevent-20791.firebaseapp.com',
    storageBucket: 'nocevent-20791.firebasestorage.app',
    measurementId: 'G-5M1BQ693B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnk5lvU3hXd_5M8d8qTyw7bNzDdD-7eN8',
    appId: '1:669049175529:android:ca65bc5f19eebf5198df78',
    messagingSenderId: '669049175529',
    projectId: 'nocevent-20791',
    storageBucket: 'nocevent-20791.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMvqsU-zA_fycER7-pgM2kcP2fai4_vsM',
    appId: '1:669049175529:ios:f8a86e24b195d33f98df78',
    messagingSenderId: '669049175529',
    projectId: 'nocevent-20791',
    storageBucket: 'nocevent-20791.firebasestorage.app',
    iosBundleId: 'com.example.nocEvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMvqsU-zA_fycER7-pgM2kcP2fai4_vsM',
    appId: '1:669049175529:ios:f8a86e24b195d33f98df78',
    messagingSenderId: '669049175529',
    projectId: 'nocevent-20791',
    storageBucket: 'nocevent-20791.firebasestorage.app',
    iosBundleId: 'com.example.nocEvent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPeamAYQmWeeOf8AX_J2rcQRRyKS22gr8',
    appId: '1:669049175529:web:ff2ff3986d924ffe98df78',
    messagingSenderId: '669049175529',
    projectId: 'nocevent-20791',
    authDomain: 'nocevent-20791.firebaseapp.com',
    storageBucket: 'nocevent-20791.firebasestorage.app',
    measurementId: 'G-TPXMKJMXG2',
  );
}
