// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpLgR7glKjSIsgT66wSxMn8FhX_4hddLM',
    appId: '1:647067484176:web:c9d3ec3e2d116a53528a95',
    messagingSenderId: '647067484176',
    projectId: 'evenvo-ba568',
    authDomain: 'evenvo-ba568.firebaseapp.com',
    storageBucket: 'evenvo-ba568.firebasestorage.app',
    measurementId: 'G-429KZ0X69X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpLgR7glKjSIsgT66wSxMn8FhX_4hddLM',
    appId: '1:647067484176:android:ANDROID_APP_ID_HERE',
    messagingSenderId: '647067484176',
    projectId: 'evenvo-ba568',
    storageBucket: 'evenvo-ba568.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpLgR7glKjSIsgT66wSxMn8FhX_4hddLM',
    appId: '1:647067484176:ios:IOS_APP_ID_HERE',
    messagingSenderId: '647067484176',
    projectId: 'evenvo-ba568',
    storageBucket: 'evenvo-ba568.firebasestorage.app',
    iosBundleId: 'com.example.evenvoMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpLgR7glKjSIsgT66wSxMn8FhX_4hddLM',
    appId: '1:647067484176:ios:IOS_APP_ID_HERE',
    messagingSenderId: '647067484176',
    projectId: 'evenvo-ba568',
    storageBucket: 'evenvo-ba568.firebasestorage.app',
    iosBundleId: 'com.example.evenvoMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpLgR7glKjSIsgT66wSxMn8FhX_4hddLM',
    appId: '1:647067484176:web:c9d3ec3e2d116a53528a95',
    messagingSenderId: '647067484176',
    projectId: 'evenvo-ba568',
    authDomain: 'evenvo-ba568.firebaseapp.com',
    storageBucket: 'evenvo-ba568.firebasestorage.app',
    measurementId: 'G-429KZ0X69X',
  );
}
