workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.evenvomobile"
      flutter: stable
    scripts:
      - name: Clean and install dependencies
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..
      - name: Build iOS app
        script: |
          flutter build ios --debug --no-codesign
