# Définir la version minimale d'iOS
platform :ios, '13.0'

# Ignorer les avertissements de CocoaPods
install! 'cocoapods', :warn_for_unused_master_specs => false

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Ajouter manuellement les dépendances Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  # Ajoute d'autres pods si tu utilises d'autres services Firebase (par exemple, Firebase/Auth, Firebase/Analytics)
end

# Post-installation pour ajuster les configurations
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end