# Définir la version minimale d'iOS
platform :ios, '13.0'

# Ignorer les avertissements de Flutter pour les pods
install! 'cocoapods', :warn_for_unused_master_specs => false

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Inclure toutes les dépendances Flutter
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

# Post-installation pour ajuster les configurations
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end